<Project>
  <PropertyGroup>
    <LangVersion>10</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' != 'Landoria.SharedLib' and '$(MSBuildProjectName)' != 'LandoriaGamePack'">
    <ILRepackTargetsFile>$(MSBuildThisFileDirectory)Landoria.SharedLib\ILRepack.targets</ILRepackTargetsFile>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'Landoria.SharedLib' and '$(MSBuildProjectName)' != 'LandoriaGamePack'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)Landoria.SharedLib\Landoria.SharedLib.csproj">
      <Private>false</Private>
    </ProjectReference>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.44">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
